export const blogsList = [
  {
    id: "4a77cbb9-4e13-4142-b2a4-1395b9c2fc80",
    title: "SPF Explained: What You’re Doing Wrong",
    content:
      "Most people misuse sunscreen. This post breaks down SPF ratings, application tips, and why reapplying matters more than you think. Many overlook the impact this has on their day-to-day energy and focus. Experts recommend small, manageable changes rather than drastic shifts. With the rise of technology, new tools are available to support this journey. Consistency and awareness are key when making lifestyle changes. Incorporating this into your routine may lead to noticeable benefits over time. The earlier you start, the greater the potential for long-term success. Individuals report improved outcomes when they combine several strategies together. It’s crucial to understand how these factors work together within the body.",
    image: "https://picsum.photos/seed/skincare1/600/400",
    createdAt: "2025-01-12T08:40:26",
    createdBy: "Dr. Ahmed Patel",
    timeToRead: "6 mins",
    category: "Skincare",
  },
  {
    id: "e6ac48f1-b398-4b35-b964-4b11cf2a73ae",
    title: "Natural Remedies for Acne That Actually Work",
    content:
      "Acne solutions don't have to come in bottles. Learn about natural ingredients like tea tree oil and zinc that show real results. It’s crucial to understand how these factors work together within the body. Individuals report improved outcomes when they combine several strategies together. Experts recommend small, manageable changes rather than drastic shifts. This insight is especially important for anyone looking to improve their long-term wellbeing. Consistency and awareness are key when making lifestyle changes. Research has consistently shown positive outcomes from implementing these practices. The earlier you start, the greater the potential for long-term success.",
    image: "https://picsum.photos/seed/skincare2/600/400",
    createdAt: "2025-02-08T11:23:19",
    createdBy: "Olivia Moore",
    timeToRead: "4 mins",
    category: "Skincare",
  },
  {
    id: "6bd17fdf-2fe5-474e-85b0-33820806a8c4",
    title: "The Science Behind Anti-Aging Products",
    content:
      "Retinoids, peptides, and antioxidants—what actually works? This article demystifies anti-aging ingredients based on real science. Experts recommend small, manageable changes rather than drastic shifts. Many overlook the impact this has on their day-to-day energy and focus. The earlier you start, the greater the potential for long-term success. With the rise of technology, new tools are available to support this journey. Consistency and awareness are key when making lifestyle changes. Research has consistently shown positive outcomes from implementing these practices. Incorporating this into your routine may lead to noticeable benefits over time.",
    image: "https://picsum.photos/seed/skincare3/600/400",
    createdAt: "2025-03-25T16:50:03",
    createdBy: "Dr. Emily Carter",
    timeToRead: "7 mins",
    category: "Skincare",
  },
  {
    id: "1d5f1d3f-c46a-4d94-8d73-6f6b8e37d69c",
    title: "How Diet Impacts Your Skin Health",
    content:
      "What you eat shows up on your face. Explore how foods like sugar, dairy, and processed fats can influence breakouts and dull skin. Individuals report improved outcomes when they combine several strategies together. It’s crucial to understand how these factors work together within the body. The earlier you start, the greater the potential for long-term success. Experts recommend small, manageable changes rather than drastic shifts. Consistency and awareness are key when making lifestyle changes. This insight is especially important for anyone looking to improve their long-term wellbeing. Research has consistently shown positive outcomes from implementing these practices.",
    image: "https://picsum.photos/seed/skincare4/600/400",
    createdAt: "2025-05-02T15:12:10",
    createdBy: "Alex Johnson",
    timeToRead: "5 mins",
    category: "Skincare",
  },
  {
    id: "baf76861-4c80-4d72-878e-0e81bacc617e",
    title: "Top 5 Serums Dermatologists Recommend",
    content:
      "From vitamin C to niacinamide, we list the most effective serums and how to choose them based on your skin type. With the rise of technology, new tools are available to support this journey. Many overlook the impact this has on their day-to-day energy and focus. Incorporating this into your routine may lead to noticeable benefits over time. Experts recommend small, manageable changes rather than drastic shifts. Individuals report improved outcomes when they combine several strategies together. It’s crucial to understand how these factors work together within the body. Consistency and awareness are key when making lifestyle changes.",
    image: "https://picsum.photos/seed/skincare5/600/400",
    createdAt: "2025-06-07T09:31:38",
    createdBy: "Sarah Bennett",
    timeToRead: "6 mins",
    category: "Skincare",
  },
  {
    id: "e2bba5ae-d245-4685-a6de-d1e12a3c0c5e",
    title: "Night vs Day Creams: Do You Need Both?",
    content:
      "Are two creams better than one? Learn why formulations differ and whether it's worth investing in separate night/day routines. Experts recommend small, manageable changes rather than drastic shifts. Individuals report improved outcomes when they combine several strategies together. This insight is especially important for anyone looking to improve their long-term wellbeing. Consistency and awareness are key when making lifestyle changes. Many overlook the impact this has on their day-to-day energy and focus. The earlier you start, the greater the potential for long-term success. Incorporating this into your routine may lead to noticeable benefits over time.",
    image: "https://picsum.photos/seed/skincare6/600/400",
    createdAt: "2025-04-10T06:18:01",
    createdBy: "Jason Lee",
    timeToRead: "5 mins",
    category: "Skincare",
  },
  {
    id: "94ad9677-022e-42df-8923-b6bc1a741a36",
    title: "Building a Skincare Routine from Scratch",
    content:
      "Overwhelmed by all the products? Start here with a step-by-step guide to crafting a basic but effective skincare routine. It’s crucial to understand how these factors work together within the body. Consistency and awareness are key when making lifestyle changes. Experts recommend small, manageable changes rather than drastic shifts. With the rise of technology, new tools are available to support this journey. Many overlook the impact this has on their day-to-day energy and focus. The earlier you start, the greater the potential for long-term success. Incorporating this into your routine may lead to noticeable benefits over time.",
    image: "https://picsum.photos/seed/skincare7/600/400",
    createdAt: "2025-03-12T10:09:00",
    createdBy: "Olivia Moore",
    timeToRead: "6 mins",
    category: "Skincare",
  },
  {
    id: "1a1d4a62-fd7b-4050-b62b-df3c5c9d28f4",
    title: "Top Skincare Trends in 2025",
    content:
      "Glass skin, skin cycling, and more—explore what’s trending and what dermatologists say about the latest skincare fads. Experts recommend small, manageable changes rather than drastic shifts. It’s crucial to understand how these factors work together within the body. Many overlook the impact this has on their day-to-day energy and focus. Individuals report improved outcomes when they combine several strategies together. Research has consistently shown positive outcomes from implementing these practices. The earlier you start, the greater the potential for long-term success. With the rise of technology, new tools are available to support this journey.",
    image: "https://picsum.photos/seed/skincare8/600/400",
    createdAt: "2025-02-28T14:42:44",
    createdBy: "Sarah Bennett",
    timeToRead: "7 mins",
    category: "Skincare",
  },
  {
    id: "cf3a4c9e-f43c-4e90-9613-7ed0060cb8b2",
    title: "Understanding Ingredients in Your Products",
    content:
      "Confused by the ingredient list? Learn how to decode labels and spot irritants, allergens, and effective actives. The earlier you start, the greater the potential for long-term success. Consistency and awareness are key when making lifestyle changes. Incorporating this into your routine may lead to noticeable benefits over time. With the rise of technology, new tools are available to support this journey. Many overlook the impact this has on their day-to-day energy and focus. Experts recommend small, manageable changes rather than drastic shifts. Research has consistently shown positive outcomes from implementing these practices.",
    image: "https://picsum.photos/seed/skincare9/600/400",
    createdAt: "2025-01-27T08:30:22",
    createdBy: "Dr. Ahmed Patel",
    timeToRead: "5 mins",
    category: "Skincare",
  },
  {
    id: "f28b7022-1f5a-46bc-9d7e-bda2533c6df5",
    title: "Skincare for Different Age Groups",
    content:
      "Your skin changes with age. Find out what ingredients and routines best suit your 20s, 30s, 40s, and beyond. Research has consistently shown positive outcomes from implementing these practices. Experts recommend small, manageable changes rather than drastic shifts. Individuals report improved outcomes when they combine several strategies together. Many overlook the impact this has on their day-to-day energy and focus. Consistency and awareness are key when making lifestyle changes. This insight is especially important for anyone looking to improve their long-term wellbeing. With the rise of technology, new tools are available to support this journey.",
    image: "https://picsum.photos/seed/skincare10/600/400",
    createdAt: "2025-05-19T11:17:36",
    createdBy: "Ethan Rivera",
    timeToRead: "6 mins",
    category: "Skincare",
  },

  {
    id: "1",
    title: "Understanding Gut Health: Why It Matters More Than You Think",
    content:
      "Gut health plays a critical role in digestion, nutrient absorption, and overall immune function. The gut microbiome, a collection of trillions of bacteria and microorganisms, is central to maintaining balance in our body. When this balance is disrupted, it can lead to a variety of health issues, including inflammation, fatigue, mood swings, and even depression. Studies have shown strong links between gut health and mental clarity. Maintaining a diverse diet rich in fiber, fermented foods, and probiotics can greatly improve gut performance. This article explores why a healthy gut isn't just about digestion—it's about whole-body wellness and mental well-being.",
    image: "https://picsum.photos/seed/healthcare1/600/400",
    createdAt: "2025-01-15T09:21:33",
    createdBy: "Dr. Ahmed Patel",
    timeToRead: "6 mins",
    category: "Healthcare",
  },
  {
    id: "2",
    title: "How to Manage Chronic Pain Without Medication",
    content:
      "Chronic pain affects millions worldwide and often leads to a dependence on painkillers. However, long-term use of medication can cause side effects and dependency. Alternative approaches like physical therapy, acupuncture, yoga, and guided meditation have proven effective in pain reduction. Cognitive Behavioral Therapy (CBT) helps patients reframe their pain experience. Building a strong support system and learning stress-reduction techniques also improve pain tolerance. This article dives into holistic approaches to managing chronic pain safely and sustainably, focusing on lifestyle and mental health strategies.",
    image: "https://picsum.photos/seed/healthcare2/600/400",
    createdAt: "2025-02-03T13:44:12",
    createdBy: "Jason Lee",
    timeToRead: "5 mins",
    category: "Healthcare",
  },
  {
    id: "3",
    title: "5 Common Myths About Health You Should Stop Believing",
    content:
      "Many widely believed health tips are actually myths. For example, carrots don’t dramatically improve night vision, and fat isn’t inherently bad. The truth is more nuanced. Skipping meals doesn’t help you lose weight—it can slow your metabolism. Cold weather doesn’t cause colds, viruses do. Detox teas often do more harm than good. In this post, we bust five health myths and explain what science really says. Understanding the truth behind these claims can help you make better health decisions every day.",
    image: "https://picsum.photos/seed/healthcare3/600/400",
    createdAt: "2025-03-20T18:32:21",
    createdBy: "Sarah Bennett",
    timeToRead: "7 mins",
    category: "Healthcare",
  },
  {
    id: "4",
    title: "The Future of Preventive Healthcare",
    content:
      "Preventive healthcare is shifting from reactive treatments to proactive measures. Innovations such as wearable tech, AI diagnostics, and personalized wellness plans are revolutionizing care. Devices can now monitor heart rate, sleep, and stress, alerting users to early signs of disease. AI helps doctors spot patterns that humans might miss. Combined with better public health awareness, preventive care is more accessible than ever. This article explores how technology is enabling earlier intervention and how it could redefine modern medicine.",
    image: "https://picsum.photos/seed/healthcare4/600/400",
    createdAt: "2025-04-11T16:07:48",
    createdBy: "Dr. Emily Carter",
    timeToRead: "6 mins",
    category: "Healthcare",
  },
  {
    id: "5",
    title: "Affordable Healthcare Tips for Families",
    content:
      "Healthcare costs can be a major burden for families. However, many strategies can help reduce expenses without compromising care. From leveraging government-subsidized clinics to comparing pharmacy prices online, small steps add up. Using telemedicine for non-emergency consultations and understanding your insurance coverage can save hundreds. Preventive care and early screenings also prevent costly treatments later. This guide highlights practical, everyday tips that help families stay healthy while keeping budgets intact.",
    image: "https://picsum.photos/seed/healthcare5/600/400",
    createdAt: "2025-02-24T10:23:02",
    createdBy: "Megan Flores",
    timeToRead: "5 mins",
    category: "Healthcare",
  },
  {
    id: "6",
    title: "Simple Lifestyle Changes That Improve Heart Health",
    content:
      "Improving heart health doesn’t require extreme changes. Small, consistent habits like walking daily, reducing salt, quitting smoking, and sleeping 7–8 hours nightly make a huge difference. Reducing processed food intake and increasing fiber supports better cholesterol levels. Managing stress through breathing exercises and reducing alcohol consumption also help. This article offers practical, doable tips to maintain cardiovascular wellness. Even moderate changes can greatly reduce the risk of heart disease.",
    image: "https://picsum.photos/seed/healthcare6/600/400",
    createdAt: "2025-06-01T08:17:15",
    createdBy: "Alex Johnson",
    timeToRead: "4 mins",
    category: "Healthcare",
  },
  {
    id: "7",
    title: "How AI Is Revolutionizing Patient Diagnosis",
    content:
      "Artificial intelligence is transforming healthcare diagnostics. By analyzing large volumes of patient data, AI helps doctors make more accurate diagnoses faster. Machine learning models can detect anomalies in X-rays, blood reports, and genetic profiles. AI chatbots are helping with triage and early screening. Hospitals are increasingly adopting AI tools to reduce diagnostic errors and improve outcomes. This post explores the real-world use of AI and what the future may hold for smarter, tech-driven diagnoses.",
    image: "https://picsum.photos/seed/healthcare7/600/400",
    createdAt: "2025-04-19T14:52:11",
    createdBy: "Ethan Rivera",
    timeToRead: "7 mins",
    category: "Healthcare",
  },
  {
    id: "8",
    title: "The Importance of Mental Health in Physical Recovery",
    content:
      "Healing isn’t just about bones and tissues—it involves the mind too. Patients who receive emotional support and practice stress management tend to recover faster. Depression and anxiety can slow physical healing. This article explains how a positive mindset, support networks, and mental health interventions like therapy improve post-surgery and chronic illness outcomes. Recognizing and treating emotional needs is essential to holistic healing.",
    image: "https://picsum.photos/seed/healthcare8/600/400",
    createdAt: "2025-03-10T07:31:08",
    createdBy: "Sarah Bennett",
    timeToRead: "5 mins",
    category: "Healthcare",
  },
  {
    id: "9",
    title: "Why Annual Checkups Still Matter in 2025",
    content:
      "Despite tech advances, annual physical exams remain crucial. They help identify silent health issues like high blood pressure or early diabetes. Preventive screenings during checkups reduce the risk of serious disease later. Doctors also assess mental health, lifestyle, and vaccination needs. This post breaks down why checkups are still the cornerstone of long-term health, even in an age of apps and wearables.",
    image: "https://picsum.photos/seed/healthcare9/600/400",
    createdAt: "2025-05-03T10:11:19",
    createdBy: "Dr. Emily Carter",
    timeToRead: "6 mins",
    category: "Healthcare",
  },
  {
    id: "10",
    title: "Top Health Habits Backed by Science",
    content:
      "Health fads come and go, but some habits are backed by solid science. Drinking plenty of water, getting 7–8 hours of sleep, regular exercise, and eating more plants are consistently proven to improve longevity and quality of life. This article compiles the most reliable, research-backed health practices that actually work. If you’re overwhelmed by wellness trends, start here with habits that matter most.",
    image: "https://picsum.photos/seed/healthcare10/600/400",
    createdAt: "2025-06-15T12:22:44",
    createdBy: "Jason Lee",
    timeToRead: "4 mins",
    category: "Healthcare",
  },

  {
    id: "uuid-meditation-1",
    title: "How Meditation Changed My Life in 30 Days",
    content:
      "After just 30 days of meditation, I noticed real changes in my mood, focus, and energy. I started with just 10 minutes a day using a guided app. Within a week, I slept better and reacted less to daily stress. I became more mindful of my thoughts, eating habits, and responses to others. My productivity improved, and I felt more in control of my emotions. Meditation gave me a mental reset I didn’t know I needed. This post shares my journey, tips for beginners, and what to expect in the first month.",
    image: "https://picsum.photos/seed/meditation1/600/400",
    createdAt: "2025-02-04T08:51:16",
    createdBy: "Sarah Bennett",
    timeToRead: "5 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-2",
    title: "Top 10 Guided Meditation Apps in 2025",
    content:
      "With so many apps available, choosing a meditation app can be tough. We tested the top 10 apps of 2025—from Calm and Headspace to Balance and Insight Timer. Each app was reviewed for ease of use, content variety, and personalization. Whether you're a beginner or experienced meditator, this guide helps you find the right fit. Plus, we cover free vs paid versions and the best ones for sleep, focus, and stress relief. If you’re ready to start or switch, this list will help.",
    image: "https://picsum.photos/seed/meditation2/600/400",
    createdAt: "2025-03-09T10:12:39",
    createdBy: "Olivia Moore",
    timeToRead: "6 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-3",
    title: "Mindfulness Techniques for Beginners",
    content:
      "Mindfulness is about being fully present. If you're new to the practice, start with mindful breathing—just observe your breath for a minute or two. Next, try a body scan, bringing awareness to each part of your body. Labeling your thoughts and returning to the present is another great tool. This article introduces 5 beginner techniques that require no experience and only a few minutes a day. Use them to manage anxiety, boost focus, and find calm amidst chaos.",
    image: "https://picsum.photos/seed/meditation3/600/400",
    createdAt: "2025-01-22T06:45:20",
    createdBy: "Jason Lee",
    timeToRead: "5 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-4",
    title: "Morning Meditation Routines for a Calm Day",
    content:
      "Starting your day with meditation sets a positive tone. Even five minutes of deep breathing or gratitude reflection can reduce stress and improve focus. Try combining meditation with journaling or stretching. This post outlines three simple morning meditation routines—one for busy schedules, one for productivity, and one for emotional clarity. Whether you're at home or commuting, these habits can help you feel more grounded, balanced, and energized all day.",
    image: "https://picsum.photos/seed/meditation4/600/400",
    createdAt: "2025-02-19T07:20:03",
    createdBy: "Alex Johnson",
    timeToRead: "6 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-5",
    title: "How Breathing Exercises Reduce Stress",
    content:
      "Breathing is one of the fastest ways to calm your nervous system. Techniques like box breathing, 4-7-8, and alternate nostril breathing can lower your heart rate and reduce anxiety. This article explains the science behind these techniques and how to practice them effectively. It also offers tips for incorporating them into your day—during work breaks, before bed, or while stuck in traffic. A few minutes of breathwork can make a big difference in how you feel.",
    image: "https://picsum.photos/seed/meditation5/600/400",
    createdAt: "2025-04-07T09:58:44",
    createdBy: "Ethan Rivera",
    timeToRead: "4 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-6",
    title: "Using Meditation to Improve Sleep",
    content:
      "Struggling with sleep? Meditation might be the solution. Practices like body scans, progressive muscle relaxation, or guided sleep meditations help quiet the mind and relax the body. This article shares the best nighttime techniques and apps for deeper rest. It also discusses how meditation improves sleep quality by reducing racing thoughts and nighttime stress. Whether you’re dealing with insomnia or just want better rest, this guide helps build a bedtime meditation routine.",
    image: "https://picsum.photos/seed/meditation6/600/400",
    createdAt: "2025-05-17T15:29:02",
    createdBy: "Dr. Emily Carter",
    timeToRead: "5 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-7",
    title: "Meditation vs. Journaling: Which is Better?",
    content:
      "Both meditation and journaling are powerful mental health tools. But which one should you choose? Meditation helps you stay present and calm the mind. Journaling helps you process thoughts and gain clarity. This article compares the benefits of each, offers combined routines, and helps you pick the best based on your personality and goals. You’ll also find tips on how to get started with either practice—even if you’ve never done it before.",
    image: "https://picsum.photos/seed/meditation7/600/400",
    createdAt: "2025-03-30T13:33:55",
    createdBy: "Megan Flores",
    timeToRead: "6 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-8",
    title: "Creating a Dedicated Meditation Space at Home",
    content:
      "A peaceful space can enhance your meditation practice. Whether it’s a corner of your bedroom or a balcony nook, setting up a dedicated space makes consistency easier. Use calming elements like cushions, plants, soft lighting, or candles. Keep it clean, quiet, and personalized. This post walks you through setting up your own meditation area with minimal cost. When your space invites you to pause and breathe, meditation becomes a daily ritual, not a chore.",
    image: "https://picsum.photos/seed/meditation8/600/400",
    createdAt: "2025-01-28T12:04:46",
    createdBy: "Dr. Ahmed Patel",
    timeToRead: "7 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-9",
    title: "Meditation for Kids: When to Start",
    content:
      "Kids can benefit from meditation too. Teaching simple breathing or visualization can help them manage emotions and focus better in school. Start with just 2-3 minutes a day, using fun animations or stories. This post explains the ideal age to begin, child-friendly apps, and common challenges parents face. Meditation builds emotional resilience from a young age, and even a few minutes can make a big impact on a child’s day.",
    image: "https://picsum.photos/seed/meditation9/600/400",
    createdAt: "2025-04-14T08:40:08",
    createdBy: "Olivia Moore",
    timeToRead: "4 mins",
    category: "Meditation",
  },
  {
    id: "uuid-meditation-10",
    title: "The Science Behind Meditation and Focus",
    content:
      "Meditation improves focus—not just by calming the mind, but by rewiring the brain. Studies show increased gray matter and stronger connections in areas linked to attention. This article explores how even short sessions improve memory, decision-making, and productivity. You’ll also learn about types of meditation best for focus and how to measure your progress. If you’re distracted easily or want to boost mental clarity, this science-backed guide is for you.",
    image: "https://picsum.photos/seed/meditation10/600/400",
    createdAt: "2025-06-05T10:47:38",
    createdBy: "Sarah Bennett",
    timeToRead: "7 mins",
    category: "Meditation",
  },

  {
    id: "uuid-sports-1",
    title: "Top 10 Fitness Trends in 2025",
    content:
      "The fitness world in 2025 is embracing technology and versatility. Wearable tech now tracks more than steps—it monitors recovery, stress, and hydration. Hybrid workouts that combine strength, cardio, and mobility are trending in both gyms and apps. Virtual coaching and AI-generated routines are becoming popular. People are focusing more on longevity and functional movement than aesthetics. This post explores the top 10 trends shaping how we train, recover, and stay fit this year.",
    image: "https://picsum.photos/seed/sports1/600/400",
    createdAt: "2025-01-17T09:22:10",
    createdBy: "Ethan Rivera",
    timeToRead: "6 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-2",
    title: "The Science of Recovery After Intense Workouts",
    content:
      "Recovery is often overlooked, but it’s when your body gets stronger. Intense training breaks down muscle fibers; recovery rebuilds them. Learn how sleep, hydration, and nutrition impact the process. We also explore techniques like foam rolling, ice baths, and active rest. Overtraining can cause burnout and injuries—recovery prevents that. This post is your guide to smart, science-backed recovery strategies that maximize performance without overdoing it.",
    image: "https://picsum.photos/seed/sports2/600/400",
    createdAt: "2025-03-05T11:35:23",
    createdBy: "Alex Johnson",
    timeToRead: "5 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-3",
    title: "How to Avoid Common Sports Injuries",
    content:
      "Injuries can sideline even the most dedicated athletes. This guide helps you prevent common ones like sprains, strains, and tendonitis. We’ll cover warm-up routines, proper technique, rest days, and gear. A lot of injuries stem from poor form or overtraining. Stretching and strength-building are crucial for joint protection. Learn how to listen to your body and make adjustments before pain becomes a problem. Prevention is better than rehab—always.",
    image: "https://picsum.photos/seed/sports3/600/400",
    createdAt: "2025-02-28T14:18:32",
    createdBy: "Dr. Ahmed Patel",
    timeToRead: "6 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-4",
    title: "Strength vs Endurance: What’s Right for You?",
    content:
      "Should you lift heavy or go the distance? Strength training builds power, increases muscle mass, and boosts metabolism. Endurance workouts like running or cycling improve heart health and stamina. Your fitness goals will guide your path—but why not both? Learn how to balance resistance training and cardio for optimal results. This article also discusses body types, training splits, and how to avoid plateaus. Pick the routine that fits your lifestyle and goals best.",
    image: "https://picsum.photos/seed/sports4/600/400",
    createdAt: "2025-04-10T17:14:50",
    createdBy: "Jason Lee",
    timeToRead: "7 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-5",
    title: "Women in Sports: Breaking Barriers in 2025",
    content:
      "2025 marks a new era for women in sports. From equal pay fights to more representation in media, female athletes are taking the spotlight. Explore key milestones this year—from Olympic wins to leadership roles in major leagues. We highlight inspiring figures and the ongoing push for equity. This post celebrates the achievements while shedding light on what still needs to change. Empowerment through sport is more than just a game—it’s a movement.",
    image: "https://picsum.photos/seed/sports5/600/400",
    createdAt: "2025-05-09T08:30:19",
    createdBy: "Sarah Bennett",
    timeToRead: "5 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-6",
    title: "How Sports Psychology Improves Performance",
    content:
      "Mental strength is just as important as physical. Sports psychology teaches athletes to manage pressure, visualize success, and stay focused. Techniques like goal-setting, self-talk, and mindfulness can boost consistency and confidence. Whether you’re a pro or just starting, understanding your mental game helps you perform better and recover faster. This post explains the psychology tools top performers use—and how you can apply them too.",
    image: "https://picsum.photos/seed/sports6/600/400",
    createdAt: "2025-01-31T07:08:11",
    createdBy: "Dr. Emily Carter",
    timeToRead: "6 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-7",
    title: "Nutrition Essentials for Athletes",
    content:
      "Fueling your body correctly can make or break your performance. Learn what to eat before, during, and after workouts. From carbs for energy to protein for recovery, this article breaks it all down. We also cover hydration, supplements, and meal timing. Every athlete has unique needs—find out how to create a nutrition plan that works for your sport and schedule. Training without proper fuel is like running a race on an empty tank.",
    image: "https://picsum.photos/seed/sports7/600/400",
    createdAt: "2025-03-17T15:27:05",
    createdBy: "Megan Flores",
    timeToRead: "4 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-8",
    title: "A Beginner's Guide to Running Form",
    content:
      "Running seems simple—but poor form can lead to injuries and inefficiency. Learn how to improve posture, stride, foot strike, and breathing. This beginner-friendly guide also covers warm-ups, cooldowns, and how to gradually increase distance. Whether you're jogging for fitness or training for a 5K, correct technique helps you run longer, faster, and pain-free. Start strong and stay safe with these essential tips.",
    image: "https://picsum.photos/seed/sports8/600/400",
    createdAt: "2025-06-06T11:01:32",
    createdBy: "Olivia Moore",
    timeToRead: "5 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-9",
    title: "The Rise of E-Sports: What You Need to Know",
    content:
      "E-sports is no longer a niche—it’s a billion-dollar industry. Professional gamers now earn salaries, attract sponsorships, and draw millions of viewers. This article explores how games like League of Legends and Valorant became global competitions. Learn about player training routines, team structures, and how mental focus plays a key role. Whether you're a gamer or just curious, this post offers an inside look into competitive gaming’s explosive growth.",
    image: "https://picsum.photos/seed/sports9/600/400",
    createdAt: "2025-04-04T13:13:13",
    createdBy: "Jason Lee",
    timeToRead: "6 mins",
    category: "Sports",
  },
  {
    id: "uuid-sports-10",
    title: "Cross-Training: Why It Works",
    content:
      "Doing the same workout every day can cause burnout and injuries. Cross-training helps by mixing activities like swimming, biking, and weight training. This improves overall fitness and keeps you mentally engaged. Learn how to build a cross-training routine that supports your goals. Whether you want to lose weight, gain strength, or stay injury-free, variety is key. This guide also covers scheduling tips and recovery strategies for multi-sport athletes.",
    image: "https://picsum.photos/seed/sports10/600/400",
    createdAt: "2025-05-23T10:22:49",
    createdBy: "Ethan Rivera",
    timeToRead: "7 mins",
    category: "Sports",
  },
];

export const categories = [
  "All",
  "Healthcare",
  "Skincare",
  "Meditation",
  "Sports",
];
